"""
flextext_generator.py — Generate FLEx .flextext import files
=============================================================
Produces a valid .flextext XML document from verse data and a pre-built
GUID map extracted from the NT Greek template project.

Each word token is linked to its WfiGloss, WfiAnalysis, or WfiWordform
in the template project by GUID, giving the same result as the LCM import:
  WfiGloss GUID    → approved gloss (green) for single-gloss words
  WfiAnalysis GUID → candidate analyses (blue) for multi-gloss words
  WfiWordform GUID → unanalysed (red) for words with no glosses
  No GUID          → new unlinked wordform created by FLEx on import

IMPORTANT — TEMPLATE COMPATIBILITY
  The generated .flextext links to objects by GUID.  Those GUIDs exist only
  in projects created from the NT Greek blank project template dated
  2026-04-19 or later.  Importing into any other project will create new
  unlinked wordforms instead of connecting to the pre-populated analyses.

Usage (standalone):
    from core.flextext_generator import generate_flextext, load_guid_map

    guid_map = load_guid_map()          # loads bundled guid_map.json
    xml_str  = generate_flextext(
        title   = 'Acts 6:1-7',
        verses  = [...],                # list of verse dicts from NT JSON
        guid_map = guid_map,
    )
    with open('Acts_6_1-7.flextext', 'w', encoding='utf-8') as f:
        f.write(xml_str)
"""

import json
import os
import unicodedata
import uuid
import xml.etree.ElementTree as ET

# ---------------------------------------------------------------------------
# GUID map loader
# ---------------------------------------------------------------------------

_GUID_MAP_CANDIDATES = [
    os.path.join(os.path.dirname(__file__), '..', 'data', 'guid_map.json'),
    os.path.join(os.path.dirname(__file__), '..', '..', 'docs', 'assets', 'data', 'guid_map.json'),
]


def load_guid_map(path: str | None = None) -> dict:
    """
    Load the surface-form → GUID map from guid_map.json.

    Args:
        path: explicit path; if None, searches standard locations.

    Returns:
        dict mapping NFC Greek surface form to
        {"guid": str, "type": str, "gls": str}
    """
    if path is not None:
        candidates = [path]
    else:
        candidates = [os.path.normpath(p) for p in _GUID_MAP_CANDIDATES]

    for p in candidates:
        if os.path.isfile(p):
            with open(p, encoding='utf-8') as f:
                return json.load(f)

    raise FileNotFoundError(
        'guid_map.json not found. '
        'Run tools/extract_guid_map.py to generate it from the template project.'
    )


# ---------------------------------------------------------------------------
# .flextext generator
# ---------------------------------------------------------------------------

_TEMPLATE_DATE = '2026-04-19'

def generate_flextext(title: str, verses: list, guid_map: dict,
                      lang_grc: str = 'grc', lang_en: str = 'en') -> str:
    """
    Generate a .flextext XML string for the given passage.

    Args:
        title:    Text title shown in FLEx (e.g. "Acts 6:1-7")
        verses:   List of verse dicts:
                    {"ref": "6:1", "words": [{"g": "Ἐν", ...}, ...],
                     "translation": "Now in these days…"}
        guid_map: Dict from load_guid_map()
        lang_grc: Language tag for Greek (default "grc")
        lang_en:  Language tag for English (default "en")

    Returns:
        UTF-8 XML string suitable for saving as a .flextext file.
    """
    doc = ET.Element('document')
    doc.set('version', '2')

    itext = ET.SubElement(doc, 'interlinear-text')
    itext.set('guid', str(uuid.uuid4()))

    # Title
    title_item = ET.SubElement(itext, 'item')
    title_item.set('type', 'title')
    title_item.set('lang', lang_en)
    title_item.text = title

    # Compatibility note as a child item — visible in the raw file
    compat_item = ET.SubElement(itext, 'item')
    compat_item.set('type', 'comment')
    compat_item.set('lang', lang_en)
    compat_item.text = (
        f'Generated by Biblical Languages for FLEx. '
        f'Word analyses link to the NT Greek blank project template '
        f'({_TEMPLATE_DATE} or later). '
        f'Importing into a project not based on that template will create '
        f'unlinked wordforms instead of connecting to pre-populated analyses.'
    )

    paragraphs_el = ET.SubElement(itext, 'paragraphs')

    n_tokens = n_linked = n_missing = 0

    for verse_num, verse in enumerate(verses, 1):
        words      = verse.get('words') or []
        trans      = (verse.get('translation') or '').strip()
        ref        = verse.get('ref', '')

        greek_tokens = [w.get('g', '').strip() for w in words if w.get('g', '').strip()]
        if not greek_tokens:
            continue

        greek_text = ' '.join(greek_tokens)

        paragraph = ET.SubElement(paragraphs_el, 'paragraph')
        paragraph.set('guid', str(uuid.uuid4()))

        phrases_el = ET.SubElement(paragraph, 'phrases')

        phrase = ET.SubElement(phrases_el, 'phrase')
        phrase.set('guid', str(uuid.uuid4()))

        # Segment surface text
        txt_item = ET.SubElement(phrase, 'item')
        txt_item.set('type', 'txt')
        txt_item.set('lang', lang_grc)
        txt_item.text = greek_text

        # Segment number
        segnum = ET.SubElement(phrase, 'item')
        segnum.set('type', 'segnum')
        segnum.set('lang', lang_en)
        segnum.text = str(verse_num)

        # Word tokens
        words_el = ET.SubElement(phrase, 'words')

        for w in words:
            surface = (w.get('g') or '').strip()
            if not surface:
                continue

            n_tokens += 1
            nfc_surface = unicodedata.normalize('NFC', surface)
            entry       = guid_map.get(nfc_surface)

            word_el = ET.SubElement(words_el, 'word')

            if entry:
                word_el.set('guid', entry['guid'])
                n_linked += 1
            else:
                # Not in map — FLEx will create a new unlinked wordform
                n_missing += 1

            tok_item = ET.SubElement(word_el, 'item')
            tok_item.set('type', 'txt')
            tok_item.set('lang', lang_grc)
            tok_item.text = surface

            # Gloss display hint (informational; FLEx uses the GUID link, not this text)
            gls_text = (entry.get('gls') or w.get('gls') or '') if entry else (w.get('gls') or '')
            if gls_text:
                gls_item = ET.SubElement(word_el, 'item')
                gls_item.set('type', 'gls')
                gls_item.set('lang', lang_en)
                gls_item.text = gls_text

        # Free translation (phrase-level)
        if trans:
            gls_item = ET.SubElement(phrase, 'item')
            gls_item.set('type', 'gls')
            gls_item.set('lang', lang_en)
            gls_item.text = trans

    # Language declarations
    languages_el = ET.SubElement(itext, 'languages')
    lang_en_el = ET.SubElement(languages_el, 'language')
    lang_en_el.set('lang', lang_en)
    lang_en_el.set('font', 'Times New Roman')
    lang_grc_el = ET.SubElement(languages_el, 'language')
    lang_grc_el.set('lang', lang_grc)
    lang_grc_el.set('font', 'Galatia SIL')
    lang_grc_el.set('vernacular', 'true')

    # Serialize
    ET.indent(doc, space='  ')
    xml_bytes = ET.tostring(doc, encoding='unicode', xml_declaration=False)
    header = '<?xml version="1.0" encoding="utf-8"?>\n'

    return header + xml_bytes, {'n_tokens': n_tokens, 'n_linked': n_linked, 'n_missing': n_missing}
